### ISSUE TITLE
No matching key. session or pairing topic doesn't exist: 

### ISSUE THREAD

**Issue by LvDj** [WalletConnect/WalletConnectFlutterV2#94] opened 2023-05-29 09:44 UTC
No matching key. session or pairing topic doesn't exist: 
walletconnect_flutter_v2: ^2.0.7

I keep waiting when I call wcClient.approveSession
ApproveResponse? respone;
        try {
          // Have been waiting ???
          respone = await wcClient.approveSession(
            id: id,
            namespaces: map,
            relayProtocol: relay.protocol,
          );
        } catch (e) {
          debugPrint("id: $id approveSession error: $e");
        }

Subsequent events cannot be received

**Comment by LvDj** [comment] 2023-05-29 12:35
There is a small chance that it will pass. Most of them will make an error

**Comment by LvDj** [comment] 2023-05-29 13:06
![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/7589988/e786cffe-6ddc-4105-a1bc-1de1764b64a8)

**Comment by LvDj** [comment] 2023-05-29 13:07
this is class Pairing;

**Comment by LvDj** [comment] 2023-05-29 13:11
But there was a strange problem. When I'm in debug breakpoint mode, I get the result, but if I don't break the point, I don't get the result

**Comment by LvDj** [comment] 2023-05-29 14:34
Looks like there was some kind of process mix-up
It succeeds because the breakpoint stops, allowing the other code to go first.

Without breakpoints, there is a problem with the process

**Comment by Luzzotica** [comment] 2023-05-30 22:45
Does deleting that await actually resolve the problem? Or does it still exist?

I was aware of this issue, and thought that I had fixed it with my most recent changed (At least, I had some tests where they would fail because of it, but 2.0.7 fixed those).

So, I guess, does deleting the await actually fix the problem without the breakpoints?
I can't imagine that it would.

**Comment by Luzzotica** [comment] 2023-05-31 21:17
I need more information.

Please provide the following:

1. The platform your dApp/wallet is running on
2. The dApp/wallet you are trying to communicate with
3. Flutter and dart version you are using

**Comment by LvDj** [comment] 2023-06-01 12:36
I ran some more tests.
If there is a breakpoint, the message can be received smoothly.
If there is no breakpoint, it cannot be received.

I initially thought it was because the breakpoint was affecting the asynchronous flow,
But when I put the breakpoint on any line, I also get a message.
This strikes me as strange.

It works on ios, but andoird will have problems

I run the wallet
I am communicating with DApp demo of WalletConnect's official website,
I also corresponded with my own DApp

Flutter 3.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d3d8effc68 (2 weeks ago) • 2023-05-16 17:59:05 -0700
Engine • revision b4fb11214d
Tools • Dart 3.0.1 • DevTools 2.23.1

**Comment by LvDj** [comment] 2023-06-01 13:37
> Does deleting that await actually resolve the problem? Or does it still exist?
> 
> I was aware of this issue, and thought that I had fixed it with my most recent changed (At least, I had some tests where they would fail because of it, but 2.0.7 fixed those). When I was resolving the issue it, it was caused because the response from the relay would be received before I could even wait for its response, which is why the relayClient.publish is not `await`ed.
> 
> So, I guess, does deleting the await actually fix the problem without the breakpoints? I can't imagine that it would.

Delete wait, cannot solve problem...
Because I added a break point. I thought it was working

**Comment by LvDj** [comment] 2023-06-01 15:29
have breakpoint:

_onMessageEvent: eb735c803c7dc1599b293fa05ec460ec3a416c02359a3b4687a241fcf47b3b0e AMwixcbBBVoUZbvbxbwuvkk/SzPdoCNQusBjJFnzQpJHsE+gYzp3FN/g0MXgFRrgqq5EtWJKdUPP26YQ+GjU4kcPP6GMD5dgO9rxmvsYKX+oRGuev07JDG7+URYq/3YBGVfHvSB4ck79ziHb11CqrFOKy9RJ1dRPiEFTy/qHqNDW815NxSM0BvaqeLR+jPuguylFi+ERtEok4Go9CLtxszUHcGgGtQXI58MZs3qANvoxipjKU1wxaVVeqrh6uVvMx7NosJmYpBljcXx/kyU/bJggIiXJvhJAK7QSste/+oTlQd57VKL2Nl/xVS/s2vXLACWthqHeWK/D8SSF+VmpozQLnD5omOCcbBeG0XpNZ4N4WQ25RRtWYE0C6/rxhpyE1FA1fecU903dpluIGAqs2fChUeTTa1wngemcFwNNN29WiqmSHMltKEgo/P8B9cavnQRX8sSehNZS9PVYvvCoUV4Ul0WL+OPtkexJxBXJKXx5k2kHvrK0TCRbucx7uPRehqvGrDnsO0ibQtEdNxo/qavIr/CVZ4QqCHBVDJgSbVHcb5ppP4P1rWzNsTIcIBhFwqMKkjyZ1sSfL9Pn3XBWQum8KwIFu9R2vS4ziNpvhghq6mP0qKVux0zQt94NVgJWmOFbL+uMcPhA2P3kfmooVE/Go/OQaoT6dh5b3VcZS1D6hC04j67PmHU9uNO+srBBYQ1SGfKTg6gkuOL2IzLDUps+DEKXAdMyityjLeTnNEeNY3KTWnkINPEpJpXavkpf1jBqY/YiIYlhtcGOYcYJxwzeqTC6UA6iQXZpj11W6F+n124WokIIgb8YWnnNdXA2Sy+y0y5Hicn9v9xknHTfnX8Bk9oEYhLAMqc3ThxzTXAcay6PGdNhEHosOTtwFNAfohLNilUNLRrxPAaiQ2Y6mt<…>
flutter: {"id":1685632991206264,"jsonrpc":"2.0","method":"wc_sessionPropose","params":{"requiredNamespaces":{"eip155":{"chains":["eip155:5"],"methods":["eth_sign","personal_sign","eth_accounts","wallet_watchAsset","wallet_switchEthereumChain","wallet_addEthereumChain","net_version","eth_sendTransaction","eth_signTransaction","eth_signTypedData","wallet_requestPermissions","eth_requestAccounts"],"events":["accountsChanged","chainChanged","disconnect"],"rpcMap":{"5":"https://rpc.walletconnect.com/v1/?chainId=eip155:5&projectId=ccfa173e846329cc001e23fa3ce2e3de"}}},"optionalNamespaces":{"eip155":{"chains":["eip155:5"],"methods":["eth_sign","personal_sign","eth_accounts","wallet_watchAsset","wallet_switchEthereumChain","wallet_addEthereumChain","net_version","eth_sendTransaction","eth_signTransaction","eth_signTypedData","wallet_requestPermissions","eth_requestAccounts"],"events":["accountsChanged","chainChanged","disconnect"],"rpcMap":{"5":"https://rpc.walletconnect.com/v1/?chainId=eip155:5&project<…>

**Comment by LvDj** [comment] 2023-06-01 15:30
The content is different. I don't know why

**Comment by Luzzotica** [comment] 2023-06-02 16:13
@LvDj Do you have a public access point for your dapp I could use?

**Comment by Luzzotica** [comment] 2023-06-02 17:53
I justed pushed out version 2.0.8, please check if it has resolved the issue.

**Comment by BrianCliton** [comment] 2023-06-02 18:36
> 我刚刚推出了2.0.8版本，请检查它是否解决了问题。

no,still have this problem

**Comment by Luzzotica** [comment] 2023-06-02 19:16
@BrianCliton 

Does it happen for every dapp you work with?
Please provide examples that I can test with. I need more information.

**Comment by Luzzotica** [comment] 2023-06-02 23:18
I can run this app: https://react-app.walletconnect.com/
Along with the example wallet and the connection is established and the session is created.
I can then request from the dapp and sign with the example wallet.

Every dapp I have tested with (That supports v2) that my example wallet can connect to establishes a connection.

So far I haven't been able to recreate this issue.

So I need more information. 

Please provide the dapp you are using along with the steps you are taking to break things.

**Comment by iota9star** [comment] 2023-06-06 04:36
@LvDj @BrianCliton I also encountered this issue. Starting from last week, I conducted a lot of repetitive and tedious tests and found that the `wc_sessionSettle` request sometimes does not receive any response, causing the entire future to wait at this step without progressing, which results in the session content not being saved. Therefore, I submitted a pull request to solve this issue and hope that you can help test it out. I am looking forward to your response.

```yaml
dependency_overrides:
  walletconnect_flutter_v2:
    git:
      url: https://github.com/iota9star/WalletConnectFlutterV2.git
      ref: "4c8a147"
```

**Comment by Luzzotica** [comment] 2023-06-06 15:27
What did you use to test it?

The changes you've made will improve the function (Based on my understanding of them), but will not actually resolve the issue of no `wc_sessionSettle`.

Please give me the tools you were using to test this. I have been unable to reproduce this on my end.

**Comment by Luzzotica** [comment] 2023-06-06 15:30
Didn't mean to close this, but I merged the changes.

I don't think this is actually resolved by the changes, I believe there is a deeper issue somewhere.

**Comment by iota9star** [comment] 2023-06-06 16:03
I think the deeper issue is that WebSocket relies heavily on network stability and code robustness to successfully send and receive messages. To complete a request during the pending process, Completer/Promise is used. If a response cannot be received, it will wait here indefinitely. In fact, we can easily identify the problem from the code.

![image](https://github.com/WalletConnect/WalletConnectFlutterV2/assets/21272154/7b335d14-66c2-4dab-9239-c4073839d786)

The code above is before submitting the PR, and we can see the part highlighted in red circle which completes the session request. After it finishes the request, it will execute the part in the green circle below. However, a problem arises here: completing the part in the red circle does not necessarily mean that the DApp has successfully received the message, or even if it has received the message, it may not yet have the topic held locally. When the request in the green circle arrives and cannot find the corresponding topic, the DApp will not respond. At this point, the green part will never get a response and will continue to wait indefinitely in this location.

**Comment by iota9star** [comment] 2023-06-06 16:08
I think it's necessary for us to add timeout interrupts to some critical methods in WalletConnect, so that even if there are problems, the code can continue to run normally instead of waiting indefinitely.

**Comment by iota9star** [comment] 2023-06-06 16:13
> I can run this app: [react-app.walletconnect.com](https://react-app.walletconnect.com/) Along with the example wallet and the connection is established and the session is created. I can then request from the dapp and sign with the example wallet.
> 
> Every dapp I have tested with (That supports v2) that my example wallet can connect to establishes a connection.
> 
> So far I haven't been able to recreate this issue.
> 
> So I need more information.
> 
> Please provide the dapp you are using along with the steps you are taking to break things.

It is easy to reproduce this issue in areas where the WalletConnect network node is not very stable. If I do not use a VPN tool, then out of ten requests, this problem may occur three or four times.

**Comment by Luzzotica** [comment] 2023-06-06 23:51
I have never had this happen and I've tested hundreds of times. I wonder why that is.

I understand unstable internet connections make things rough, but using websocket/TCP should remove this issue. We use them _because_ they ensure the complete arrival of a packet.

I believe it is more of a race condition as you've described it.

I'll mark this as closed, but I still feel like the underlying issue hasn't been resolved, the fact that it fails 30-40% of the time is not promising to me.

**Closed by Luzzotica** 2023-06-06 23:51 UTC

**Comment by LvDj** [comment] 2023-06-07 10:22
@Luzzotica I am in China and need vpn to connect to walletconnect. But you must have a direct Internet connection, so I don't know if that has anything to do with it

**Comment by dmdeklerk** [comment] 2023-06-07 11:56
I can confirm that calling Web3Wallet.approveSession sometimes returns a result and sometimes it does not.
We are in the Netherlands where the (inhouse) dapp and wallet app run on the same top quality internet connection.

I can see the DApp receiving the approve session message but the wallet remains hanging waiting for the response from the Web3Wallet.approveSession call.

This happens 4 out of 10 times approx.
