### ISSUE TITLE
Request: Method to identify duplicate connections to the same peer

### ISSUE THREAD

**Issue by bobwith2bees** [WalletConnect/WalletConnectFlutterV2#83] opened 2023-05-17 21:10 UTC
If the answer is "It's a privacy thing, so - No.  There is no unique identifier" , just let me know.  ;-)

Here is what I would like to do:

When a user connects to a wallet, I would like the ability to check if there is now a duplicate relay connection to the same peer (wallet app on a single device.)  This way I have an easier time supporting and tracing requests to the end wallet.  (I might disconnect the prior connection and associated sessions for example.)

I understand a user may connect to the same wallet app on multiple devices, so using the peer metadata seems insufficient.

It's a lower priority for my DAPP, because I could limit my app connecting to only a single wallet at a time.  (i.e. disconnect all sessions so I know there are no duplicates.)

**Comment by bobwith2bees** [comment] 2023-05-17 21:20
Cross posted to the WalletConnect Discussion https://github.com/orgs/WalletConnect/discussions/2410

**Comment by Luzzotica** [comment] 2023-05-19 17:57
I'm not sure I understand precisely what you're asking for.

Let's give an example to see if I have understood.

1. Dapp on Computer 1, connects to wallet on mobile device A
2. Dapp on mobile device A connects to wallet on mobile device A

There are now two connections in the wallet to the same Dapp.

Are you wanting to disconnect one of the sessions? Or am I wrong?

**Comment by bobwith2bees** [comment] 2023-05-19 18:38
I am more looking to detect a misbehaving / misconfigured app.   Or simply an unexpected state.

1. Dapp on mobile device A connects to wallet on mobile device A
2. Dapp on mobile device A connects to wallet on mobile device A
 - Two pairings existing between the same two peers.

Can you programmatically detect two pairings from the same peer?   It is possible the user re-installs the Dapp and loses the initial pairing config.  Could the wallet detect the older pairing and consider remediation?  I know the old pairing will expire eventually.   I just wanted to add a warning in my code if I happened to detect it.

Interop testing with all these wallets - I am getting all sorts of unexpected combinations of state.  :-/

**Comment by Luzzotica** [comment] 2023-05-23 22:53
It is not possible to detect duplicate pairings unless you're working from the same dApp and the same wallet. Only that dApp and wallet will have the pairing stored, and only they will be aware of and able to use any sessions on top of it.

This is purposeful for privacy reasons: don't want dApps/Wallets to be able to query pairings that were established for others.

A question:
Is the Dapp and Wallet the same Dapp and Wallet each time?
Let's give them some names to be explicit:
- Dapp X on mobile device A connects to wallet Y on mobile device A
- Dapp Z on mobile device A connects to wallet Y on mobile device A

Two pairings, but there are technically 3 different peers here, as each Dapp is treated as its own peer, the wallet as a third.
A "peer" is not a device.
A "peer" is a WalletConnect enabled Dapp or wallet.

**Comment by Luzzotica** [comment] 2023-06-02 18:03
I'm going to close this, as the request is not possible by design.
Hopefully my descriptions above make that clear.

**Closed by Luzzotica** 2023-06-02 18:03 UTC
