### ISSUE TITLE
No matching key. session topic doesn't exist:

### ISSUE THREAD

**Issue by BrianCliton** [WalletConnect/WalletConnectFlutterV2#96] opened 2023-06-02 07:35 UTC
always appear: No matching key. session topic doesn't exist:
walletconnect_flutter_v2: ^2.0.7

It is the error reported here, it may be caused by timing problems： https://github.com/WalletConnect/WalletConnectFlutterV2/blob/db3287aa962b1a5d14f2f5de655a9fc495b26412/lib/apis/core/pairing/pairing.dart#L411

**Comment by LvDj** [comment] 2023-06-02 07:53
Your problem is the same problem I have

https://github.com/WalletConnect/WalletConnectFlutterV2/issues/94

**Comment by Luzzotica** [comment] 2023-06-02 17:58
Yes, duplicate of #94

**Comment by Luzzotica** [comment] 2023-06-06 15:29
Didn't mean to close this, but I merged the changes. 

I don't think this is actually resolved by the changes, I believe there is a deeper issue somewhere.

**Closed** 2023-06-06 15:30 UTC
